//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UriAgassi.Isobars.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UriAgassi.Isobars.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5, 0.7, 1.1, 1.6, 1.9, 2.3, 2.1, 1.7, 1.3, 0.9, 2.1, 2.6, 3.1, 3.6, 4.1, 4.5, 4.7, 5.0, 4.8, 4.5, 4.1, 3.7, 4.1
        ///0.7, 1.5, 2.3, 2.0, 1.9, 2.1, 1.9, 1.4, 1.1, 0.7, 1.7, 2.1, 2.7, 3.1, 3.6, 4.1, 4.5, 4.8, 4.5, 4.1, 3.9, 3.5, 3.8
        ///1.2, 1.7, 1.9, 1.7, 2.1, 2.3, 2.1, 1.7, 1.4, 1.1, 1.4, 1.9, 2.4, 2.7, 3.3, 3.8, 4.3, 4.5, 4.3, 3.9, 3.7, 3.4, 3.7
        ///1.5, 1.9, 1.7, 2.1, 2.3, 2.5, 2.3, 2.1, 1.8, 1.5, 1.8, 2.1, 2.5, 3.0, 3.5, 4.0, 4.5, 4.7, 4.5, 4.3, 4.1, 3.8, 3.5
        ///1.9, 2.1, 2.3, 2.5, 2.7, 2.9, 2.5, 2.3, 2.1, 1.9, 2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
    }
}
